apiVersion: v1
kind: LimitRange
metadata:
  name: core-resource-limit
  namespace: default
spec:
  limits:
  - default:
      cpu: "2"
      memory: "9Gi"
      ephemeral-storage: "8Gi"
    defaultRequest:
      cpu: "1"
      memory: "4Gi"
      ephemeral-storage: "4Gi"
    type: Container