apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerSet
metadata:
  name: dm-next-api-runner-set
  namespace: actions-runner-system
spec:
  ephemeral: true
  replicas: 1
  repository: Dealermade/dm-next-api
  serviceName: dm-next-api
  dockerdWithinRunnerContainer: true
  # dockerMTU: 1450
  labels:
    - dm-next-api-runner
  selector:
    matchLabels:
      app: dm-next-api
  template:
    metadata:
      labels: 
        app: dm-next-api
    spec:
      containers:
        - name: runner
          env:
            - name: RUNNER_FEATURE_FLAG_EPHEMERAL
              value: 'true'
          imagePullPolicy: Always
          resources:
            limits:
              cpu: '2.0'
              memory: 2Gi
              ephemeral-storage: 4Gi
            requests:
              cpu: '1.0'
              memory: 1Gi
              ephemeral-storage: 2Gi
        # - name: docker
        #   resources:
        #     limits:
        #       cpu: '1.0'
        #       memory: 2Gi
        #       ephemeral-storage: 4Gi
        #     requests:
        #       cpu: '0.5'
        #       memory: 1Gi
        #       ephemeral-storage: 2Gi