# runnerdeployment.yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: dm-next-api-runner-deployment
  namespace: actions-runner-system
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    spec:
      repository: Dealermade/dm-next-api
      # organization: Dealermade
      # group: Default
      # serviceAccountName: aws-node
      # securityContext:
      #   fsGroup: 27
      imagePullPolicy: Always
      # resources:
      #   limits:
      #     ephemeral-storage: "1Gi"
      #   requests:
      #     ephemeral-storage: "500Mi"      
      ephemeral: true
      labels:
        - dm-next-api-runner
      env: 
        - name: RUNNER_FEATURE_FLAG_EPHEMERAL
          value: "true"
        - name: DISABLE_WAIT_FOR_DOCKER
          value: "true"